---
- name: Practicing Loops in Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: print names in Loops
    ansible.builtin.debug:
      msg: "Hello, {{ item }}!"
    loop:
      - Alice
      - Bob
      - Charlie
      - Diana